# questions.py
questions = {
    'Python': [
        ("Question 1: Who developed Python?",
         [("A", "Guido van Rossum"), ("B", "James Gosling"), ("C", "Dennis Ritchie"), ("D", "Bjarne Stroustrup")],
         "A"),
        ("Question 2: Python is named after:",
         [("A", "A species of snake"), ("B", "Monty Python's Flying Circus (British comedy series)"), ("C", "The Greek letter π (pi)"), ("D", "A mathematical concept")],
         "B"),
        ("Question 3: Which of the following is NOT a key characteristic of Python mentioned in the notes?",
         [("A", "Interpreted"), ("B", "Interactive"), ("C", "Compiled"), ("D", "Object-Oriented")],
         "C"),
        ("Question 4: How do you display the full Zen of Python in the Python shell?",
         [("A", "print(zen)"), ("B", "import this"), ("C", "from zen import *"), ("D", "zen()")],
         "B"),
        ("Question 5: What was the release year of Python 3.0?",
         [("A", "2000"), ("B", "2006"), ("C", "2008"), ("D", "2010")],
         "C"),
        ("Question 6: What is the code to print \"Hello World\" in Python?",
         [("A", "echo \"Hello World\""), ("B", "printf(\"Hello World\")"), ("C", "print(\"Hello World\")"), ("D", "System.out.println(\"Hello World\")")],
         "C"),
        ("Question 7: Which of the following is a popular application area where Python is widely used according to the notes?",
         [("A", "Low-level system programming"), ("B", "Data Science and Machine Learning"), ("C", "Operating system kernel development"), ("D", "Real-time embedded firmware")],
         "B"),
        ("Question 8: In Python, how are code blocks defined?",
         [("A", "Using curly braces {}"), ("B", "Using indentation (spaces or tabs)"), ("C", "Using semicolons ;"), ("D", "Using parentheses ()")],
         "B"),
        ("Question 9: How do you denote a private variable in a Python class (by convention)?",
         [("A", "_variable"), ("B", "__variable"), ("C", "variable_"), ("D", "$variable")],
         "B"),
        ("Question 10: Which built-in function is used to convert a string like \"123\" to an integer?",
         [("A", "float()"), ("B", "str()"), ("C", "int()"), ("D", "complex()")],
         "C"),
        ("Question 11: Which of the following is the correct way to write an octal integer literal in Python?",
         [("A", "034"), ("B", "0o34"), ("C", "0x34"), ("D", "#34")],
         "B"),
        ("Question 12: What is the value of the hexadecimal literal 0x1C in decimal?",
         [("A", "16"), ("B", "24"), ("C", "28"), ("D", "34")],
         "C"),
        ("Question 13: Which literal represents a complex number?",
         [("A", "10.5"), ("B", "\"Hello\""), ("C", "2 + 3j"), ("D", "[1, 2, 3]")],
         "C"),
        ("Question 14: How are multi-line string literals defined in Python?",
         [("A", "Using single quotes ' '"), ("B", "Using double quotes \" \" "), ("C", "Using triple quotes ''' or \"\"\""), ("D", "Using parentheses ( )")],
         "C"),
        ("Question 15: What is the type of the literal (1, \"Ravi\", 75.50, True)?",
         [("A", "list"), ("B", "dict"), ("C", "tuple"), ("D", "set")],
         "C"),
        ("Question 16: Which built-in function converts a string \"10.5\" to a float?",
         [("A", "int()"), ("B", "str()"), ("C", "float()"), ("D", "complex()")],
         "C"),
        ("Question 17: In Python classes, how is a private variable conventionally defined?",
         [("A", "_var (protected)"), ("B", "__var (private with name mangling)"), ("C", "var (public)"), ("D", "#var")],
         "B"),
        ("Question 18: What is the recommended way to create a Python virtual environment (as per modern practice)?",
         [("A", "python -m virtualenv .venv"), ("B", "python -m venv .venv"), ("C", "pip install venv"), ("D", "virtualenv create .venv")],
         "B"),
        ("Question 19: What is the current stable version of Python as of December 22, 2025?",
         [("A", "Python 3.11.2"), ("B", "Python 3.13"), ("C", "Python 3.14.2"), ("D", "Python 3.15")],
         "C"),
        ("Question 20: Which encoding is the default for Python 3 source code and strings?",
         [("A", "ASCII"), ("B", "UTF-16"), ("C", "UTF-8"), ("D", "Latin-1")],
         "C"),
    ],
    'JavaScript': [],  # Add similar lists for other categories
    'SQL': [],
    'Git': [],
    'CSS and HTML': []
}